[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "AERzip"
version = "0.8.0"
description = "Useful tools to compress and decompress AEDAT files in Python"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Álvaro Ayuso Martínez", email = "aayuso@us.es"}
]
dependencies = [
  "pyNAVIS"
]

[project.urls]
"Repository" = "https://github.com/alvayus/AERzip"